Khasa22 patch 1
khasa22/COTORRA pull request #4
Opened 2022-04-25 09:53 UTC by khasa22

network delay equation: double summation ...
Have confusion how exactly encode it

2022-04-25 10:48 UTC, khasa22 commented
#

2022-04-28 10:17 UTC, MartinPJorge requested changes
On top of the comments, I would suggest that we use same notation as in the paper.

For example, rather than `throughput` we should use `lambda`. That'd make easier to follow the problem formulation and AMPL encoding. You can use comments to clarify what lambda is.

2022-04-28 10:17 UTC, MartinPJorge commented on res-opt.mod
> +param Pdelay{s1 in S,vf in VNF[s1]}:= sum {(v1,v2)in ES} vf_throughput[v1,v2]*c[vf];
What is this parameter?

You are summing over the multiplication of `vf_throughput[v1,v2]*c[vf]` which has units `[Mbps]*CPU`.
Such product cannot give a delay and we don't use this anywhere in the formulation, right?

2022-04-28 10:17 UTC, MartinPJorge commented on res-opt.mod
> +param attachment{r,R} binary;
The radio attachment should be a decision variable, not a parameter.

2022-04-28 10:17 UTC, MartinPJorge commented on res-opt.mod
> +        (sum {vf in VNF[s1]} if avf[s1,vf,n]==1 then c[vf])
You can replace the if statement as follows:
```ampl
sum {vf in VNF[s1]} avf[s1,vf,n] * c[s1, vf]
```

2022-04-28 10:17 UTC, MartinPJorge commented on res-opt.mod
> +# vertices (VNFs) of service graph
These are the edges of the service graph.

I'd rename it as `VLs`.

2022-04-28 10:17 UTC, MartinPJorge commented on res-opt.mod
> +# vertices (VNFs) of service graph
On top, the edges should be defined for a particular service graph. Refactor `set ES ...` to be:
```ampl
set VLs{s in S} := {v1 in VNF[s], v2 in VNF[s]};
```

2022-04-28 10:17 UTC, MartinPJorge commented on res-opt.mod
> +# vertices (VNFs) of service graph
Update accordingly lines below to be consistent with the new definition.

2022-04-28 10:17 UTC, MartinPJorge commented on res-opt.mod
> +param Pdelay{s1 in S,vf in VNF[s1]}:= sum {(v1,v2)in ES} vf_throughput[v1,v2]*c[vf];
Although we do, we should change it to the avg. latency of an M/M/1 system -- see the overleaf.

2022-04-28 10:17 UTC, MartinPJorge commented on res-opt.mod
> +var avl{ES,E} binary ;
You have to redefine it to consider the service. Something like:
```ampl
var avl {Si in S, VLs[Si], E} binary;
```

2022-04-28 10:17 UTC, MartinPJorge commented on res-opt.mod
> +        (sum {s1 in S,vf in VNF[s1],n in N} if avf[s1,vf,n]==1 then vf_throughput[v1,v2]);
Replace this summation over virtual links by:

Same as above, replace the if statement using the product:
```ampl
sum {Si in S} sum {(v1,v2) in VLs[Si]}  avl[Si, v1,v2, n1,n2] * vf_throughput[Si, v1,v2];
```

2022-04-28 10:17 UTC, MartinPJorge commented on res-opt.mod
> +                                    sum {v in VNF[s1]} avf[s1,v,n]*c[v] <= comput_res[n];
The placement constraint should apply to all services deployed within the node, i.e.:
```ampl
subject to placement {n in N}:
  sum {Si in S} sum {v in VNF[Si]} avf[Si,v,n] * c[Si,v] <= comput_res[n];
```

2022-04-28 10:17 UTC, MartinPJorge commented on res-opt.mod
> +param c { v in S};
A VNF is not within the set of services, but within the set of VNFs of a particular service, therefore, it should be something like:
```ampl
param c {Si in S, v in VNFs[Si] };
```

2022-04-28 10:17 UTC, MartinPJorge commented on res-opt.mod
> +param vf_throughput{ES};
Same for the throughput, to obtain a set of VLs from a service we need which service `Si` we talk about:
```ampl
param vf_throughput { Si in S, VLs[Si] };
```

2022-04-28 10:17 UTC, MartinPJorge commented on res-opt.mod
> +                                        sum {(v1, v2) in ES} vf_throughput[v1,v2] <=throughput[n1,n2];
Here we miss to iterate over all possible services, as in the placement constraint above:
```ampl
                             sum {Si in S} sum {(v1,v2) in VLs[Si]}  vf_throughput[Si, v1,v2] <=throughput[n1,n2];
```

2022-04-28 10:17 UTC, MartinPJorge commented on res-opt.mod
> +                                        sum {(v1,v2) in ES} vf_throughput[v1,v2]<= T[i,p];
As above, we miss the service indexing:
```ampl
subject to PoA_feasiblity{i in r, p in R}:
                                        sum {Si in S} sum {(v1,v2) in VL[Si]} vf_throughput[Si, v1,v2]<= T[i,p];
```

2022-04-28 10:17 UTC, MartinPJorge commented on res-opt.mod
> +                        sum {v in VNF[j]} Pdelay[j,v] + sum {(v1,v2) in ES} Ndelay[v1,v2] <=DS[j];
Use the service indexing to iterate over the VLs:
```ampl

subject to delay{j in S}:
                        sum {v in VNF[j]} Pdelay[j,v] + sum {(v1,v2) in VLs[j]} Ndelay[v1,v2] <=DS[j];
```

2022-05-03 17:03 UTC, merged